pipeline {
  agent any

  stages {
    stage('Run in Docker') {
      steps {
        sh 'sudo docker pull node:16-alpine'
        sh 'sudo docker run --rm node:16-alpine node --version'
      }
    }
  }
}
